# SwiftLint Configuration for GitCthulhu

# 包含的路徑
included:
  - Sources/
  - Tests/

# 排除的路徑
excluded:
  - .build/
  - .swiftpm/
  - DerivedData/
  - Package.swift

# 禁用的規則
disabled_rules:
  - trailing_whitespace # 由 pre-commit hooks 處理

# 可選規則（預設未啟用但我們要啟用）
opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition

# 自訂規則配置
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - url
    - uri
    - api
    - ui
    - db

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# 檔案標頭配置
file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*\.swift
                    \/\/ GitCthulhu
                    \/\/
                    \/\/ Created by .* on \d{4}-\d{2}-\d{2}\.
                    \/\/

# 客製化訊息
custom_rules:
  no_print:
    name: "No Print Statements"
    regex: '\bprint\s*\('
    message: "Use Logger instead of print statements"
    severity: warning

  no_force_cast:
    name: "No Force Cast"
    regex: '\bas!\s'
    message: "Avoid force casting, use safe casting instead"
    severity: error

  git_commit_convention:
    name: "Git Commit Convention"
    regex: '(?i)(fix|feat|docs|style|refactor|test|chore)(\(.+\))?: .+'
    message: "Follow conventional commit format"
    severity: warning

# 警告閾值
warning_threshold: 5
error_threshold: 10

# 報告格式
reporter: "xcode"
