name: Setup Project

on:
  workflow_dispatch:
    inputs:
      setup_type:
        description: 'Setup type'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - labels
          - milestones
          - issues

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make scripts executable
        run: |
          chmod +x .github/scripts/*.sh

      - name: Authenticate GitHub CLI
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Setup Labels
        if: ${{ github.event.inputs.setup_type == 'all' || github.event.inputs.setup_type == 'labels' }}
        run: |
          .github/scripts/setup-labels.sh

      - name: Setup Milestones
        if: ${{ github.event.inputs.setup_type == 'all' || github.event.inputs.setup_type == 'milestones' }}
        run: |
          .github/scripts/setup-milestones.sh

      - name: Create Sprint 0 Issues
        if: ${{ github.event.inputs.setup_type == 'all' || github.event.inputs.setup_type == 'issues' }}
        run: |
          .github/scripts/create-sprint0-issues.sh
